Repository fabrica-bayarea/prontuario-back, pull requests merged in 2024-09, with the labels that each got.

#46 test e2e corrigido, ref #43
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: Low Priority

#50 Correção da validação do rota Atendimento #39
  src/atendimento/atendimento.service.ts
Labels: Medium Priority

#54 adcionado novas colunas nas tabelas, close #52
  prisma/schema.prisma
  src/atendimento/atendimento.dto.ts
  src/auth/auth.service.ts
  src/auth/dto/auth.dto.ts
  src/curso/curso.dto.ts
  src/curso/curso.service.ts
  src/main.ts
  src/programa/programa.dto.ts
  src/programa/programa.service.ts
Labels: enhancement, Critical Priority

#56 Feat conteinerização, close #45
  Dockerfile
  README.md
  docker-compose-dev.yml
  docker-compose.yml
  prisma/migrations/20240927014139_novas_colunas_usuario_programa_curso/migration.sql
  src/curso/curso.dto.ts
  src/curso/curso.service.ts
Labels: enhancement, Medium Priority

#57 versão nova postgres e nome correto de service, close #45
  README.md
  docker-compose-dev.yml
  docker-compose.yml
Labels: bug
